id: suricata
name: Suricata
author: Tenzir
author_icon: https://github.com/tenzir.png

description: |
  A package to simplify the onboarding of logs emitted from a Suricata
  instance.

inputs:
  eve-path:
    description: A path where suricata writes eve.json formatted logs
    type: string
    default: /var/lib/suricata/eve.sock

pipelines:
  import:
    name: Suricata Import
    description: Ingest Suricata events into the internal storage of the node.
    retry_on_error: 5m
    definition: |
      from file ${{ inputs.eve-path }} --follow read suricata
      | import

snippets:
  - name: Todays Alerts
    description: Display all Suricata alerts from the last 24 hours.
    definition: |
      export
      | where #schema == "suricata.alert"
      | where #import_time > 1 day ago
