name: Suricata
author: tenzir

description: |
  A package to simplify the onboarding of logs emitted from a Suricata
  instance.

inputs:
  eve-path:
    description: A path where suricata writes eve.json formatted logs
    type: string
    default: /var/lib/suricata/eve.sock
  restart-on-failure:
    description: |
      Whether the import should be restarted if a failure occurs in the
      pipeline.
    type: bool
    default: true

pipelines:
  import:
    name: Suricata Import
    description: Ingest Suricata events into the internal storage of the node.
    definition: |
      from file ${{ inputs.eve-path }} --follow read suricata
      | import
    autostart:
      created: true
      failed: ${{ inputs.restart-on-failure }}
    labels:
      - Suricata

snippets:
  - name: Todays Alerts
    description: Display all Suricata alerts from the last 24 hours.
    definition: |
      export
      | where #schema == "suricata.alert"
      | where #import_time > 1 day ago
