name: Feodo Abuse Blocklist
author: tenzir

description: |
  Feodo Tracker is a project of abuse.ch with the goal of sharing botnet C&C
  servers associated with Dridex, Emotet (aka Heodo), TrickBot, QakBot (aka
  QuakBot / Qbot) and BazarLoader (aka BazarBackdoor). It offers various
  blocklists, helping network owners to protect their users from Dridex and
  Emotet/Heodo.

contexts:
  feodo:
    type: lookup-table


pipelines:
  update-context:
    name: Update Feodo Context
    description: blab
    autostart:
      created: true
    definition: |
      every 1 hour { 
        from https://feodotracker.abuse.ch/downloads/ipblocklist_aggressive.csv read csv --allow-comments
        | context update feodo --key=dst_ip --clear
      } | discard


charts:
  feodo:
    definition: |
      show contexts | where name == "feodo" | chart gauge --value=num_entries


snippets:
  - name: Lookup Feodo
    description: Evaluate data with a `src_ip` field against the Feodo Blocklist.
    definition: |
      lookup feodo --field=dst_ip
  - name: Enrich Feodo
    definition: |
      export | enrich feodo --field=dst_ip
